### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 6

### ISSUE THREAD

**Issue by fadlurhmn** [kj89/testnet_manuals#9]
root@sei-fad:~# seid status 2>&1 | jq .SyncInfo
parse error: Invalid numeric literal at line 1, column 6

**Comment by kj89** [comment]
Did you run 
source $HOME/.bash_profile

**Comment by fadlurhmn** [comment]
Last login: Thu Jun 16 16:40:41 2022 from 110.138.0.95
root@sei-fad:~# source $HOME/.bash_profile
root@sei-fad:~# seid status 2>&1 | jq .SyncInfo
parse error: Invalid numeric literal at line 1, column 6

**Comment by kj89** [comment]
Check the logs

**Comment by fadlurhmn** [comment]
root@sei-fad:~# journalctl -u seid -f -o cat
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00125c140, 0xa})
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        /root/sei-chain/cmd/seid/main.go:15 +0x31
seid.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
seid.service: Failed with result 'exit-code'.

seid.service: Scheduled restart job, restart counter is at 136.
Stopped seid.
Started seid.
5:02PM INF starting node with ABCI Tendermint in-process
5:02PM INF Starting multiAppConn service impl=multiAppConn module=proxy
5:02PM INF Starting localClient service connection=query impl=localClient module=abci-client
5:02PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
5:02PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
5:02PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
5:02PM INF Starting EventBus service impl=EventBus module=events
5:02PM INF Starting PubSub service impl=PubSub module=pubsub
5:02PM INF Starting IndexerService service impl=IndexerService module=txindex
5:02PM INF ABCI Handshake App Info hash="��b-����䭬Sū3g��\x03�\b�;����Q�|�\x1f" height=153758 module=consensus protocol-version=0 software-version=1.0.2beta
5:02PM INF ABCI Replay Blocks appHeight=153758 module=consensus stateHeight=153758 storeHeight=153759
5:02PM INF Replay last block using real app module=consensus
5:02PM ERR UPGRADE "1.0.3beta" NEEDED at height: 153759:
panic: UPGRADE "1.0.3beta" NEEDED at height: 153759:  [recovered]
        panic: UPGRADE "1.0.3beta" NEEDED at height: 153759:
goroutine 1 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
        /root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.6.3/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000035200, {0x0, 0x0, 0x33dc4e0?})
        /root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.6.3/trace/span.go:398 +0x8dd
panic({0x19a52c0, 0xc0005a2070})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc001057f40, 0xa}, 0xc000cf5dd0, {0x25a66d8, 0xc00102ffe0}, {0x25c5dc8, 0xc000d47720}, 0xc00054dcb0, {0x25a08c0, 0xc0000c0b60}, ...}, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/abci.go:71 +0xf9f
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x25ba358, 0xc000052060}, {0x25c7460, 0xc00067f340}, {{0xb, 0x0}, {0xc0011fe2f0, 0xd}, 0x2589f, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x3a2
github.com/sei-protocol/sei-chain/app.(*App).BeginBlocker(_, {{0x25ba358, 0xc000052060}, {0x25c7460, 0xc00067f340}, {{0xb, 0x0}, {0xc0011fe2f0, 0xd}, 0x2589f, ...}, ...}, ...)
        /root/sei-chain/app/app.go:691 +0x85
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0006171c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011fe2f0, 0xd}, 0x2589f, {0x30e0b517, ...}, ...}, ...})
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x97c
github.com/sei-protocol/sei-chain/app.(*App).BeginBlock(_, {{0xc0006171c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011fe2f0, 0xd}, 0x2589f, {0x30e0b517, ...}, ...}, ...})
        /root/sei-chain/app/abci.go:17 +0x3a5
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0006171c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011fe2f0, 0xd}, 0x2589f, {0x30e0b517, ...}, ...}, ...})
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0006171c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0011fe2f0, 0xd}, 0x2589f, {0x30e0b517, ...}, ...}, ...})
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x25bb3f8?, 0xc00007d020}, {0x25c0ab0, 0xc000d01c30}, 0xc0000010e0, {0x25c66f8, 0xc000d01000}, 0x2589e?)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0006156f0, 0x7}}, {0xc000615700, 0xd}, 0x1, 0x2589e, {{0xc0000ddf00, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0006156f0, 0x7}}, {0xc000615700, 0xd}, 0x1, 0x2589e, {{0xc0000ddf00, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0006156f0, 0x7}}, {0xc000615700, 0xd}, 0x1, 0x2589e, {{0xc0000ddf00, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000f8bfd0, {0x25c7cc0, 0xc000cc4820})
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0006156f0, 0x7}}, {0xc000615700, 0xd}, 0x1, 0x2589e, ...}, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000508640, {0x25b71c0, 0xc0012ff540}, 0xc0011b0360, {0x25a18a0, 0xc000ef1d10}, 0x0?, 0x0?, 0xc0011b0570, {0x25bb3f8, ...}, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x25ce468, 0xc000cf4cf0}, {0xc000c2db30, 0xd}, {0x25bea10, 0xc0011b0ed0}, ...}, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001237400?, {0x3412508?, 0x0?, 0x0?})
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc001237400, {0x3412508, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001202500)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc001057f40, 0xa})
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        /root/sei-chain/cmd/seid/main.go:15 +0x31
seid.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
seid.service: Failed with result 'exit-code'.

**Comment by kj89** [comment]
Try this
https://github.com/kj89/testnet_manuals/tree/main/sei#chain-upgrade-from-102beta-to-103beta
